[dependencies]
gast = "0.5.3"
iree-compiler = { version = "20240226.813", numpy = "Any", PyYAML = "Any" }
iree-runtime = { version = "20240226.813", numpy = "Any", PyYAML = "Any" }
pybind11 = "2.10.4"
pytest = { version = "7.4.0", iniconfig = "Any", packaging = "Any", pluggy = ">=0.12,<2.0" }