# use IREE image as base image
FROM gcr.io/iree-oss/base:latest

# get IREE source code
WORKDIR /root
RUN git clone https://github.com/openxla/iree.git
RUN cd iree && git submodule update --init

# install conda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \ 
    && rm -f Miniconda3-latest-Linux-x86_64.sh
RUN export PATH="/root/miniconda/bin:$PATH"
RUN conda init

# install AINL python deps
RUN conda install pybind11
RUN conda install cmake
RUN conda install pytest
RUN conda install gast




