name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: mkdir ${{github.workspace}}/build && cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Build libainl
        run: cd ${{github.workspace}}/build && make

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ./runtest