name: Build AILang Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ailang-build .

      - name: Run Docker container and Build AILang
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace ailang-build /bin/bash -c "
          pwd
          ls -l
          # Build AILang
          cd /workspace/AILang && \
          pip install -r python/requirement.txt && \
          pip install -e python
          "
